import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import cv2

class GradCAM:
    def __init__(self, model, layer_name=None):
        """
        Initialize GradCAM
        
        Args:
            model (tf.keras.Model): Model to visualize
            layer_name (str, optional): Name of the layer to use for GradCAM
        """
        self.model = model
        
        # If layer name is not provided, use the last convolutional layer
        if layer_name is None:
            for layer in reversed(model.layers):
                if 'conv' in layer.name:
                    layer_name = layer.name
                    break
        
        self.layer_name = layer_name
        self.grad_model = self._make_grad_model()
        
    def _make_grad_model(self):
        """
        Create a model that outputs the activation maps and model prediction
        
        Returns:
            tf.keras.Model: Gradient model
        """
        conv_layer = self.model.get_layer(self.layer_name)
        grad_model = tf.keras.models.Model(
            inputs=[self.model.inputs],
            outputs=[conv_layer.output, self.model.output]
        )
        return grad_model
    
    def compute_heatmap(self, image, class_idx=None, eps=1e-8):
        """
        Compute GradCAM heatmap
        
        Args:
            image (numpy.ndarray): Input image (should match model input shape)
            class_idx (int, optional): Index of the class to visualize. If None, use prediction.
            eps (float): Small value to avoid division by zero
            
        Returns:
            numpy.ndarray: Generated heatmap
        """
        # Expand dimensions to create a batch of one
        image_batch = np.expand_dims(image, axis=0)
        
        # Record operations on grad tape
        with tf.GradientTape() as tape:
            conv_output, predictions = self.grad_model(image_batch)
            
            if class_idx is None:
                class_idx = tf.argmax(predictions[0])
            
            class_output = predictions[:, class_idx]
        
        # Compute gradients with respect to feature map
        grads = tape.gradient(class_output, conv_output)
        
        # Take the mean of gradients (GAP)
        pooled_grads = tf.reduce_mean(grads[0], axis=(0, 1))
        
        # Weight feature maps with gradients
        conv_output = conv_output[0]
        heatmap = tf.reduce_sum(tf.multiply(pooled_grads, conv_output), axis=-1)
        
        # ReLU on heatmap
        heatmap = np.maximum(heatmap, 0)
        
        # Normalize heatmap
        heatmap = heatmap / (np.max(heatmap) + eps)
        
        return heatmap.numpy()
    
    def overlay_heatmap(self, image, heatmap, alpha=0.5, colormap=cv2.COLORMAP_JET):
        """
        Overlay heatmap on original image
        
        Args:
            image (numpy.ndarray): Original image
            heatmap (numpy.ndarray): Heatmap generated by compute_heatmap
            alpha (float): Transparency factor for overlay
            colormap: OpenCV colormap
            
        Returns:
            numpy.ndarray: Image with heatmap overlay
        """
        # Resize heatmap to match image size
        heatmap = cv2.resize(heatmap, (image.shape[1], image.shape[0]))
        
        # Ensure image is in 0-255 uint8 format
        if image.dtype != np.uint8:
            if np.max(image) <= 1.0:
                image = (image * 255).astype(np.uint8)
            else:
                image = image.astype(np.uint8)
        
        # Convert heatmap to RGB
        heatmap = np.uint8(255 * heatmap)
        heatmap = cv2.applyColorMap(heatmap, colormap)
        
        # Convert if necessary
        if len(image.shape) == 2 or image.shape[2] == 1:
            image = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
        
        # Overlay heatmap on image
        superimposed = cv2.addWeighted(image, 1-alpha, heatmap, alpha, 0)
        
        return superimposed
    
    def visualize(self, image, class_idx=None, alpha=0.5, save_path=None):
        """
        Compute and visualize GradCAM
        
        Args:
            image (numpy.ndarray): Input image
            class_idx (int, optional): Index of the class to visualize
            alpha (float): Transparency factor for overlay
            save_path (str, optional): Path to save the visualization
            
        Returns:
            numpy.ndarray: Image with heatmap overlay
        """
        # Prepare image for model
        model_img = cv2.resize(image, (self.model.input_shape[1], self.model.input_shape[2]))
        
        # Preprocess for model if needed (assuming input in 0-1 range)
        if np.max(model_img) > 1.0:
            model_img = model_img / 255.0
        
        # Generate heatmap
        heatmap = self.compute_heatmap(model_img, class_idx)
        
        # Convert image to RGB if grayscale
        if len(image.shape) == 2:
            image = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
        
        # Overlay heatmap
        superimposed = self.overlay_heatmap(image, heatmap, alpha)
        
        # Plot
        plt.figure(figsize=(12, 4))
        
        plt.subplot(1, 3, 1)
        plt.imshow(image)
        plt.title('Original Image')
        plt.axis('off')
        
        plt.subplot(1, 3, 2)
        plt.imshow(heatmap, cmap='jet')
        plt.title('GradCAM Heatmap')
        plt.axis('off')
        
        plt.subplot(1, 3, 3)
        plt.imshow(superimposed)
        plt.title('GradCAM Overlay')
        plt.axis('off')
        
        plt.tight_layout()
        
        if save_path:
            plt.savefig(save_path)
            
        plt.show()
        
        return superimposed