# ia/src/visualization/pneumonia_detection_gui_with_heatmap.py
import os
import sys
import tkinter as tk
from tkinter import filedialog, messagebox
import cv2
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from tensorflow.keras.models import load_model
from PIL import Image, ImageTk
import tensorflow as tf

class GradCAM:
    def __init__(self, model, last_conv_layer_name=None):
        """
        Initialize GradCAM with a model
        
        Args:
            model: Tensorflow model
            last_conv_layer_name: Name of the last convolutional layer. If None, will try to find it automatically.
        """
        self.model = model
        
        # Si le nom de la dernière couche convolutionnelle n'est pas fourni, la trouver automatiquement
        if last_conv_layer_name is None:
            for layer in reversed(model.layers):
                # Chercher la dernière couche convolutionnelle
                if 'conv' in layer.name:
                    last_conv_layer_name = layer.name
                    break
        
        if last_conv_layer_name is None:
            raise ValueError("Could not find a convolutional layer in the model")
            
        self.last_conv_layer_name = last_conv_layer_name
        self.grad_model = self._create_grad_model()
        
    def _create_grad_model(self):
        """Create a model that maps from the input image to conv layer outputs and the predicted class"""
        # Créer un modèle qui renvoie la sortie de la dernière couche conv et la sortie du modèle
        grad_model = tf.keras.models.Model(
            inputs=[self.model.inputs], 
            outputs=[
                self.model.get_layer(self.last_conv_layer_name).output, 
                self.model.output
            ]
        )
        return grad_model
        
    def generate_heatmap(self, img_array, class_idx=None):
        """
        Generate a heatmap for the specified class
        
        Args:
            img_array: Preprocessed image (4D array)
            class_idx: Index of the class for which to generate the heatmap. If None, uses the predicted class.
            
        Returns:
            heatmap: Normalized heatmap
        """
        # Prédire la classe et les activations de la dernière couche conv
        with tf.GradientTape() as tape:
            last_conv_output, preds = self.grad_model(img_array)
            if class_idx is None:
                class_idx = tf.argmax(preds[0])
            class_channel = preds[:, class_idx]
            
        # Calculer le gradient de la classe par rapport à la sortie de la couche conv
        grads = tape.gradient(class_channel, last_conv_output)
        
        # Vector of mean intensity of gradients over feature map channels
        pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
        
        # Multiplier chaque canal par l'importance de ce canal
        last_conv_output = last_conv_output[0]
        heatmap = last_conv_output @ pooled_grads[..., tf.newaxis]
        heatmap = tf.squeeze(heatmap)
        
        # Normaliser la heatmap
        heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap)
        return heatmap.numpy()
        
    def overlay_heatmap(self, img, heatmap, alpha=0.5):
        """
        Overlay the heatmap on the original image
        
        Args:
            img: Original image (not preprocessed)
            heatmap: Heatmap generated by generate_heatmap
            alpha: Opacity of the heatmap
            
        Returns:
            superimposed_img: Original image with heatmap overlay
        """
        # Redimensionner la heatmap à la taille de l'image originale
        heatmap = cv2.resize(heatmap, (img.shape[1], img.shape[0]))
        
        # Convertir la heatmap en RGB
        heatmap = np.uint8(255 * heatmap)
        heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
        
        # Superposer la heatmap sur l'image originale
        superimposed_img = heatmap * alpha + img
        superimposed_img = np.uint8(np.clip(superimposed_img, 0, 255))
        
        return superimposed_img, heatmap


class PneumoniaDetectionGUI:
    def __init__(self, root, model_path):
        """
        Initialize the GUI application
        
        Args:
            root: Tkinter root window
            model_path (str): Path to the trained model file
        """
        self.root = root
        self.root.title("Pneumonia Detection System")
        self.root.geometry("1000x800")
        self.root.configure(bg="#f0f0f0")
        
        # Load model
        try:
            # Chargement du modèle avec custom_objects si nécessaire
            self.model = load_model(model_path)
            print(f"Model loaded successfully from {model_path}")
            
            # Initialiser GradCAM
            self.gradcam = GradCAM(self.model)
            print("GradCAM initialized")
            
        except Exception as e:
            messagebox.showerror("Error", f"Failed to load model: {e}")
            root.destroy()
            return
        
        self.img_size = 224  # Expected input size for the model
        self.classes = ['NORMAL', 'PNEUMONIA']
        
        # Create GUI components
        self.create_widgets()
        
        # Currently loaded image
        self.current_image_path = None
        self.current_image = None
        self.original_img = None  # Pour stocker l'image originale
        
        # Variables pour suivre les widgets du heatmap
        self.heatmap_heading = None
        
    def create_widgets(self):
        """Create GUI widgets"""
        # Title
        title_label = tk.Label(
            self.root, 
            text="Pneumonia Detection System", 
            font=("Arial", 18, "bold"),
            bg="#f0f0f0",
            pady=10
        )
        title_label.pack()
        
        # Frame for buttons
        button_frame = tk.Frame(self.root, bg="#f0f0f0")
        button_frame.pack(pady=10)
        
        # Load image button
        self.load_btn = tk.Button(
            button_frame,
            text="Load X-ray Image",
            command=self.load_image,
            font=("Arial", 12),
            bg="#4CAF50",
            fg="white",
            padx=10,
            pady=5
        )
        self.load_btn.pack(side=tk.LEFT, padx=10)
        
        # Predict button
        self.predict_btn = tk.Button(
            button_frame,
            text="Predict & Generate Heatmap",
            command=self.predict_and_generate_heatmap,
            font=("Arial", 12),
            bg="#2196F3",
            fg="white",
            padx=10,
            pady=5,
            state=tk.DISABLED  # Disabled until an image is loaded
        )
        self.predict_btn.pack(side=tk.LEFT, padx=10)
        
        # Main frame for images (contains original and heatmap)
        main_frame = tk.Frame(self.root, bg="#f0f0f0")
        main_frame.pack(fill=tk.BOTH, expand=True, padx=20, pady=10)
        
        # Frame for original image
        self.image_frame = tk.Frame(main_frame, bg="white", width=400, height=400)
        self.image_frame.pack(side=tk.LEFT, fill=tk.BOTH, expand=True, padx=5)
        
        # Label for displaying original image
        self.image_label = tk.Label(self.image_frame, bg="white")
        self.image_label.pack(fill=tk.BOTH, expand=True)
        
        # Frame for heatmap
        self.heatmap_frame = tk.Frame(main_frame, bg="white", width=400, height=400)
        self.heatmap_frame.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True, padx=5)
        
        # Créer un conteneur pour le titre du heatmap
        self.heatmap_heading_container = tk.Frame(self.heatmap_frame, bg="white")
        self.heatmap_heading_container.pack(side=tk.TOP, fill=tk.X)
        
        # Label for displaying heatmap
        self.heatmap_label = tk.Label(self.heatmap_frame, bg="white")
        self.heatmap_label.pack(fill=tk.BOTH, expand=True)
        
        # Frame for prediction results
        result_frame = tk.Frame(self.root, bg="#f0f0f0")
        result_frame.pack(pady=10, fill=tk.X)
        
        # Label for prediction result
        self.result_var = tk.StringVar()
        self.result_var.set("No prediction yet")
        
        result_label = tk.Label(
            result_frame,
            textvariable=self.result_var,
            font=("Arial", 14),
            bg="#f0f0f0",
            pady=10
        )
        result_label.pack()
        
        # Status bar
        self.status_var = tk.StringVar()
        self.status_var.set("Ready")
        
        status_bar = tk.Label(
            self.root,
            textvariable=self.status_var,
            bd=1,
            relief=tk.SUNKEN,
            anchor=tk.W
        )
        status_bar.pack(side=tk.BOTTOM, fill=tk.X)
    
    def load_image(self):
        """Load an image file"""
        # Open file dialog to select an image
        filetypes = [
            ("Image files", "*.jpg *.jpeg *.png"),
            ("All files", "*.*")
        ]
        
        image_path = filedialog.askopenfilename(
            title="Select X-ray Image",
            filetypes=filetypes
        )
        
        if image_path:
            try:
                # Read and display the image
                self.display_image(image_path)
                self.current_image_path = image_path
                self.status_var.set(f"Image loaded: {os.path.basename(image_path)}")
                self.predict_btn.config(state=tk.NORMAL)  # Enable predict button
                self.result_var.set("No prediction yet")
                
                # Reset heatmap display and clean previous heading
                self.clear_heatmap_display()
                
            except Exception as e:
                messagebox.showerror("Error", f"Failed to load image: {e}")
                self.status_var.set("Failed to load image")
    
    def clear_heatmap_display(self):
        """Clear the heatmap display and any associated labels"""
        # Effacer l'image du heatmap
        self.heatmap_label.config(image="")
        self.heatmap_label.image = None
        
        # Effacer le titre du heatmap s'il existe
        for widget in self.heatmap_heading_container.winfo_children():
            widget.destroy()
    
    def display_image(self, image_path):
        """Display the loaded image"""
        # Read image using CV2 for processing
        self.original_img = cv2.imread(image_path)
        
        # Convert BGR to RGB for display
        rgb_img = cv2.cvtColor(self.original_img, cv2.COLOR_BGR2RGB)
        
        # Read image using PIL for displaying
        img = Image.fromarray(rgb_img)
        
        # Resize to fit the frame while maintaining aspect ratio
        width, height = img.size
        max_size = 400
        
        if width > height:
            new_width = max_size
            new_height = int(height * (max_size / width))
        else:
            new_height = max_size
            new_width = int(width * (max_size / height))
        
        # Resize and convert to PhotoImage
        img = img.resize((new_width, new_height), Image.LANCZOS)
        self.current_image = ImageTk.PhotoImage(img)
        
        # Update label
        self.image_label.config(image=self.current_image)
        self.image_label.image = self.current_image  # Keep a reference
        
        # Réinitialiser la bordure de l'image
        self.image_label.config(borderwidth=0, relief=tk.FLAT)
    
    def preprocess_image(self, img_path=None, img=None):
        """
        Preprocess image for prediction
        
        Args:
            img_path: Path to the image file (used if img is None)
            img: Image array (used if provided)
            
        Returns:
            Preprocessed image array
        """
        if img is None and img_path is not None:
            # Read image
            img = cv2.imread(img_path)
        
        if img is None:
            raise ValueError("Either img_path or img must be provided")
        
        # Convert to grayscale (pour correspondre au prétraitement du modèle)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Apply CLAHE (Contrast Limited Adaptive Histogram Equalization)
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        clahe_img = clahe.apply(gray)
        
        # Resize to the expected size
        resized = cv2.resize(clahe_img, (self.img_size, self.img_size))
        
        # Normalize to [0, 255]
        normalized = cv2.normalize(resized, None, 0, 255, cv2.NORM_MINMAX)
        
        # Convert back to 3 channels for compatibility with the model
        img_3channels = cv2.cvtColor(normalized, cv2.COLOR_GRAY2RGB)
        
        # Normalize pixel values to [-1, 1] as dans data_loader.py
        img_3channels = img_3channels / 127.5 - 1
        
        # Add batch dimension
        img_3channels = np.expand_dims(img_3channels, axis=0)
        
        return img_3channels
    
    def predict_and_generate_heatmap(self):
        """Make prediction and generate heatmap for the loaded image"""
        if not self.current_image_path or self.original_img is None:
            messagebox.showinfo("Info", "Please load an image first")
            return
        
        try:
            self.status_var.set("Processing...")
            self.root.update()
            
            # Nettoyer l'affichage du heatmap précédent
            self.clear_heatmap_display()
            
            # Preprocess image
            preprocessed_img = self.preprocess_image(img=self.original_img)
            
            # Make prediction with the model
            prediction = self.model.predict(preprocessed_img)
            
            # Get class index and probability
            class_idx = np.argmax(prediction[0])
            probability = prediction[0][class_idx]
            
            predicted_class = self.classes[class_idx]
            
            # Update result
            result_text = f"Prediction: {predicted_class}\nConfidence: {probability:.2%}"
            self.result_var.set(result_text)
            
            # Color code the result (green for normal, red for pneumonia)
            if predicted_class == "NORMAL":
                self.image_label.config(borderwidth=5, relief=tk.SOLID, bd=5, highlightbackground="green", highlightcolor="green")
            else:
                self.image_label.config(borderwidth=5, relief=tk.SOLID, bd=5, highlightbackground="red", highlightcolor="red")
            
            # Generate heatmap
            heatmap = self.gradcam.generate_heatmap(preprocessed_img, class_idx)
            
            # Overlay heatmap on original image
            superimposed_img, raw_heatmap = self.gradcam.overlay_heatmap(self.original_img, heatmap)
            
            # Convert to RGB for display
            superimposed_rgb = cv2.cvtColor(superimposed_img, cv2.COLOR_BGR2RGB)
            
            # Convert numpy array to PIL Image
            heatmap_img = Image.fromarray(superimposed_rgb)
            
            # Resize to fit the frame while maintaining aspect ratio
            width, height = heatmap_img.size
            max_size = 400
            
            if width > height:
                new_width = max_size
                new_height = int(height * (max_size / width))
            else:
                new_height = max_size
                new_width = int(width * (max_size / height))
            
            # Resize and convert to PhotoImage
            heatmap_img = heatmap_img.resize((new_width, new_height), Image.LANCZOS)
            heatmap_tk = ImageTk.PhotoImage(heatmap_img)
            
            # Add a heading above the heatmap in the container
            heading = f"Heatmap: Red areas show regions most influencing {predicted_class} prediction"
            heading_label = tk.Label(
                self.heatmap_heading_container, 
                text=heading, 
                font=("Arial", 10),
                bg="white"
            )
            heading_label.pack(side=tk.TOP)
            self.heatmap_heading = heading_label
            
            # Update heatmap label
            self.heatmap_label.config(image=heatmap_tk)
            self.heatmap_label.image = heatmap_tk  # Keep a reference
            
            self.status_var.set(f"Prediction complete: {predicted_class} with heatmap generated")
            
        except Exception as e:
            import traceback
            print(traceback.format_exc())
            messagebox.showerror("Error", f"Prediction or heatmap generation failed: {e}")
            self.status_var.set("Prediction failed")

def main():
    # Trouver les chemins du projet
    current_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(current_dir)))
    ia_root = os.path.dirname(os.path.dirname(current_dir))  # Racine du dossier ia/
    
    # Chemins possibles du modèle
    model_paths = [
        os.path.join(ia_root, "models", "pneumonia_model_best.h5"),  # Le modèle entraîné
        os.path.join(project_root, "models", "pneumonia_model_best.h5"),  # Alternative
        # os.path.join(ia_root, "models", "resnet50_base.h5")  # Modèle de base si le premier n'existe pas
    ]
    
    # Trouver le premier modèle qui existe
    model_path = None
    for path in model_paths:
        if os.path.exists(path):
            model_path = path
            break
    
    if not model_path:
        print("No model found. Please train the model first using preprocess_and_train.py")
        sys.exit(1)
    
    print(f"Using model: {model_path}")
    
    # Create Tkinter root
    root = tk.Tk()
    
    # Create app
    app = PneumoniaDetectionGUI(root, model_path)
    
    # Run app
    root.mainloop()

if __name__ == "__main__":
    main()